import webbrowser

print("who's there?")
user_name = input()

if user_name == "ur mum":
    print("ok")
else:
    while 3 > 2:
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        while 3 > 2:
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            webbrowser.open_new('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
