print("What is name comrade?")
user_name = input()

if user_name == "Vadim blyat":
    print("ok")
else:
    while 3 > 2:
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        f = open("F.txt", "r")
        print(f.read())
        f = open("F2.txt", "r")
        print(f.read())
        f = open("F3.txt", "r")
        print(f.read())
        f = open("F4.txt", "r")
        print(f.read())
        while 3 > 2:
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
            f = open("F.txt", "r")
            print(f.read())
            f = open("F2.txt", "r")
            print(f.read())
            f = open("F3.txt", "r")
            print(f.read())
            f = open("F4.txt", "r")
            print(f.read())
